spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testapi?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://cdb-5jxq3ux4.bj.tencentcdb.com:10030/testapi?serverTimezone=UTC
#    username: root
#    password: fbz961110
#    driver-class-name: com.mysql.cj.jdbc.Driver


file:
  md:
    originPath: /md/**
    toPath: file:/d:/medias/media_md/
    path: d:/medias/media_md/
  image:
    cache: d:/medias/media_image_cache/
    originPath: /image/**
    toPath: file:/d:/medias/media_pic/
    path: d:/medias/media_pic/
    name: 20
url:
  basic: /api/**

random:
  file:
    name:
      limit: 20


